version: '3.8'

services:
  # Serviço do MySQL
  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - ./banco_de_dados:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Serviço do PHP com Apache
  php:
    build: .
    container_name: php-apache-container
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./src:/var/www/html

networks:
  app-network:
    driver: bridge
